version: "3.9"

services:
  srv-postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - vol-postgres:/var/lib/postgresql/data
    networks:
      - net-transcendence
    env_file:
      - .env

  srv-backend:
    container_name: backend
    image: backend:1.0
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - net-transcendence
    depends_on:
      - srv-postgres
    env_file:
      - .env

  srv-frontend:
    container_name: frontend
    image: frontend:1.0
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - net-transcendence
    env_file:
      - .env

networks:
  net-transcendence:
    name: net-transcendence
    driver: bridge

volumes:
  vol-postgres:
    name: postgres
